# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 1
# Label requiring a response
responseRequiredLabel: 'MISSING : INFORMATION :mag:'
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  ### No Response :-1:

  This issue has been automatically closed because there has been no response
  to our request for more information from the original author. Kindly provide 
  requested information so that we can investigate this issue further.