language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
    - os: windows
      addons:
        apt:
          sources:
            - ppa:jonathonf/ffmpeg-4
          packages:
            - ffmpeg
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: "2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    # Obtain Python 3.7 from xenial as per https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      dist: xenial
install: 
  # Get newer pip and whell for binary caching support
  - pip install --upgrade pip wheel
  - pip install .
  - pip install --upgrade pytest
  - pip install --upgrade youtube-dl
  - pip install pytest-cov
  - pip install codecov
script: 
  - pytest --cov=vidgear --cov-report term-missing tests/
after_success:
  - codecov
cache: pip
