--- 
language: python
before_install: 
  - "sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y"
  - "sudo apt-get update -q"
  - "sudo apt-get install ffmpeg -y"
branches: 
  only: 
    - testing
cache: pip
install: 
  - "pip install --upgrade pip wheel"
  - "pip install ."
  - "pip install --upgrade pytest"
  - "pip install --upgrade youtube-dl"
dist: xenial
python: 
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
script: 
  - pytest -sv